# Generated by Django 5.0.7 on 2024-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_income_source_alter_accountbalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
