# Generated by Django 5.0.7 on 2024-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Cafe&Restaurant', 'Cafe&Restaurant'), ('Foods', 'Foods'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
