# Generated by Django 5.0.7 on 2024-07-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
    ]
